[tool.poetry]
name = "nukeserversocket"
version = "0.5.0"
description = ""
authors = ["virgilsisoe <virgilsisoe@gmail.com>"]
packages = [
    { include = "src" },
]

[tool.poetry.dependencies]
python = ">=3.6, <=3.7.7"
PySide2 = "<=5.12.2"

[tool.poetry.dev-dependencies]
pytest = "~6.2.5"
pytest-qt = "~4.0.2"
requests = "~2.26.0"
pytest-cov = "~3.0.0"
pytest-randomly = "^3.10.1"
six = "^1.16.0"
pytest-repeat = "^0.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
